// <auto-generated />
namespace RMS.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class LeaveProfile_Entity_Extended : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LeaveProfile_Entity_Extended));
        
        string IMigrationMetadata.Id
        {
            get { return "201607150650016_LeaveProfile_Entity_Extended"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
