// <auto-generated />
namespace RMS.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_Payroll_Start_End_days_of_Month_to_SysConfig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_Payroll_Start_End_days_of_Month_to_SysConfig));
        
        string IMigrationMetadata.Id
        {
            get { return "201608020913132_Added_Payroll_Start_End_days_of_Month_to_SysConfig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
