// <auto-generated />
namespace RMS.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Removed_ShiftPattern_Agency_and_AgencyWorker_Entities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Removed_ShiftPattern_Agency_and_AgencyWorker_Entities));
        
        string IMigrationMetadata.Id
        {
            get { return "201609061622148_Removed_ShiftPattern_Agency_and_AgencyWorker_Entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
