// <auto-generated />
namespace RMS.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Added_Reason_and_Notes_fields_to_ShiftProfile_Entity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_Reason_and_Notes_fields_to_ShiftProfile_Entity));
        
        string IMigrationMetadata.Id
        {
            get { return "201605100841309_Added_Reason_and_Notes_fields_to_ShiftProfile_Entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
