USE [master]
GO

/****** Object:  Database [zktime]    Script Date: 20/03/2016 11:16:15 ******/
DROP DATABASE [zktime]
GO

/****** Object:  Database [zktime]    Script Date: 20/03/2016 11:16:15 ******/
CREATE DATABASE [zktime]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'zktime', FILENAME = N'C:\Users\John\zktimedb\zktime.mdf' , SIZE = 24576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'zktime_log', FILENAME = N'C:\Users\John\zktimedb\zktime_log.ldf' , SIZE = 388544KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [zktime] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [zktime].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [zktime] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [zktime] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [zktime] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [zktime] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [zktime] SET ARITHABORT OFF 
GO

ALTER DATABASE [zktime] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [zktime] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [zktime] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [zktime] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [zktime] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [zktime] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [zktime] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [zktime] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [zktime] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [zktime] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [zktime] SET  DISABLE_BROKER 
GO

ALTER DATABASE [zktime] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [zktime] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [zktime] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [zktime] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [zktime] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [zktime] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [zktime] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [zktime] SET RECOVERY FULL 
GO

ALTER DATABASE [zktime] SET  MULTI_USER 
GO

ALTER DATABASE [zktime] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [zktime] SET DB_CHAINING OFF 
GO

ALTER DATABASE [zktime] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [zktime] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [zktime] SET  READ_WRITE 
GO